### ISSUE TITLE
VcdApiClient returns empty data with System Admin role

### ISSUE THREAD

**Issue by TekiYoung** [vmware/vcd-ext-sdk#89] opened 2019-07-31 06:19 UTC
**Describe the bug**
VcdApiClient returns empty data with System Admin.
If with Org Admin, the returned data are correct.

**To Reproduce**
(vCD 9.7)
1. Login to /provider portal using System Admin account
2. Open Tenant portal from Organizations grid link
3. Make a call to API using VcdApiClient
4. The response is 200 OK yet with empty 'record' field

Please see attached image showing different data with identical request URL.
![returned-data-comparison](https://user-images.githubusercontent.com/29425502/62187923-76730e80-b39d-11e9-8bc7-87bc4cf7e637.png)

**Expected behavior**
VcdApiClient returns same data for System Admin and Org Admin roles

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version @vcd/sdk@0.9.0, vCloud 9.7, API Version=31.0

**Additional context**
None

**Comment by jmoroski** [comment] 2019-07-31 14:56
This is addressed in Pull Request #84.

The actAs functionality is what will allow the expected behavior, by automatically adding `X-VMWARE-VCLOUD-TENANT-CONTEXT` request header to the API request when a provider has navigated to a tenant UI.

Note that without this header, the underlying API is working as intended (whether or not the behavior is _expected_ is another matter). Without the header, non-admin query requests (type=vm vs. type=adminVm) are always made in the org context of the user making the request. So when a System admin makes a type=vm request without the header, it will _always_ return 0 records because VMs can't be created in the System context.

The pull request will be part of a published NPM version in the near future.

**Closed by jmoroski** 2019-07-31 14:56 UTC

**Comment by TekiYoung** [comment] 2019-08-01 05:50
Thank you, it worked!
Though type=adminVM is case-sensitive, otherwise vCD throws exceptions.
