### ISSUE TITLE
Missing locale data for the locale "fr" for the DatePipe error

### ISSUE THREAD

**Issue by neha-gupta12** [vmware/vcd-ext-sdk#269] opened 2023-03-10 06:32 UTC
**Describe the bug**
The customer is getting this issue on using the French language on the VCD extension plugin v2. This is a kind of intermittent issue. I am not facing the same on my environment but trying to fix the same.

**To Reproduce**
1. Set your Chrome browser language as French
2. In the VCD extension
3. Open the plugin Data Management V2 and connect to the CDM endpoint and open Reports (Rapports);
4. It gives the error.

I am trying to resolve the same. I added the following code on AppModule, but this change doesn't let the plugin install on VCD.

`import localeFr from '@angular/common/locales/fr';
registerLocaleData(localeFr);`
```
 providers: [
    { provide: LOCALE_ID, useValue: navigator.language },
```

Also added the pipes this way, still no luck
`{{ snapshot.date | date: 'medium':undefined:locale }}`

**Expected behavior**
The data should be visible in French locale, for date and percentage fields without giving such console errors.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Additional context**
I think we need to add some imports in the root main module.

**Comment by nvladimirovi** [comment] 2023-03-10 07:54
What pipe are you using to format the date and percentage?

**Comment by neha-gupta12** [comment] 2023-03-10 09:41
I am using Angular pipes
`import { CommonModule, DatePipe, PercentPipe, registerLocaleData } from '@angular/common';`

**Comment by nvladimirovi** [comment] 2023-03-10 11:17
Okey I'll need some time to reproduce the issue and will keep you updated.

**Comment by nvladimirovi** [comment] 2023-03-15 07:04
We found the cause of the issue will try to fix it in next patch release, which version of Cloud Director you are using?

**Comment by neha-gupta12** [comment] 2023-03-15 09:30
Thanks for the update, we are using 10.2 Cloud Director version.

**Comment by nvladimirovi** [comment] 2023-03-15 13:42
I reproduced the issue in 10.4, Cloud Director 10.2 is out of support. I'll try to reproduce it in 10.3 and fix it there also if reproducible.

**Comment by neha-gupta12** [comment] 2023-03-16 17:20
Yeah correct, We are using the pipes same way you shared. We have imported the CommonModule in our app module.

**Comment by nvladimirovi** [comment] 2023-03-22 07:51
The issue is fixed in later releases, did you find a workaround for the issue?
I'd suggest implementing your own version of those pipes for now and later removing them when you have a newer Cloud Director version.

**Comment by neha-gupta12** [comment] 2023-03-22 08:41
The customer is using 10.4.1 version, so is the issue fixed on that? If it will take more time then we can implement the workaround.

**Comment by nvladimirovi** [comment] 2023-03-22 08:43
No, the CU will have to upgrade to 10.4.2 to get the fix. The reason for that is that UI Plugins function differently from 10.4 and higher.

**Comment by neha-gupta12** [comment] 2023-03-22 09:05
Sure thanks, I will try to test the plugin on the later versions of VCD.

**Closed** 2023-03-22 13:37 UTC
