### ISSUE TITLE
After saving using the Atom editor, the built and deployed plugin will no longer function.

### ISSUE THREAD

**Issue by kvalenti** [vmware/vcd-ext-sdk#41] opened 2018-09-27 17:22 UTC
**Describe the bug**
When saving using the Atom editor, Atom automatically creates 2 files for each XX.ts file: XX.js and XX.js.map.  When those files are present, the "yarn run deploy" process incorporates those files into the bundle.js file.  Next, when the plugin is deployed to the vCD environment, it will fail with an error.

**To Reproduce**
1. Open Atom
2. Make a changes to any .ts file and then save it.  _Notice: Atom will create two new files in the same directory, X.js and X.js.map._
3. Run **yarn run build**.  _Notice: the contents of X.js will mostly be inside the dist/bundle.js file._
4. Deploy the plugin in a vCD environment, using **yarn run deploy.**
5. Load the vCD environment and open the developer tools.  _Notice: there is an error saying "Could not load external extensions.  Error: No ResourceLoader implementation has been provided.  Can't read the url 'XX.html'"_

**Expected behavior**
Files saved using Atom should be ignored by the rollup process.  

**Screenshots**
![image](https://user-images.githubusercontent.com/1268062/46163062-1c269000-c258-11e8-8fed-9f322a06fca3.png)

**Desktop (please complete the following information):**
 - OS: High Sierra
 - Browser: chrome, firefox

**Additional context**
Adding **"outDir": "build",** to the compilerOptions in the tsconfig.json file seemed to fix the issue.

**Comment by jmoroski** [comment] 2018-11-30 20:32
Closing this issue as unable to reproduce, as verified in reporter's environment.

Please feel free to reopen if problem persists.

**Closed by jmoroski** 2018-11-30 20:32 UTC
Labels: bug, unable-to-reproduce
