### ISSUE TITLE
[@vcd/ext-cli] Building a plugin with lerna does not show compilation errors

### ISSUE THREAD

**Issue by irahov** [vmware/vcd-ext-sdk#213] opened 2021-07-08 07:36 UTC
**Describe the bug**
Building the plugin with lerna does not show compilation errors

**To Reproduce** 
1. Create a new plugin `vcd-ext new` https://vmware.github.io/vcd-ext-sdk/docs/ui_plugins/getting_started
2. Make some changes in plugin itself that result in compilation error.
3. Run `npm run build` in the top folder that is using `"build": "lerna run build",`
Observed: there is no compilation error although there is such
Expected: compilation error to be shown
4. Navigate to the plugin `cd packages/YOUR_PLUGIN_NAME`
5.  Run `npm run build`
Observed: the compilation error is shown
**Expected behavior**

**Comment by mslavov** [comment] 2021-07-08 07:39
Is this happening with building a UI plugin?
If so, the issue is with the angular compiler, since it shows complication errors but exits with exit code 0, which is what learn looks at. I'm not sure we can do something about it, except wrapping the `ng build` scanning the output for errors.

**Comment by irahov** [comment] 2021-07-08 14:30
Yes, it is for an UI plugin.

**Comment by nvladimirovi** [comment] 2022-02-14 10:30
Fixed by https://github.com/vmware/vcd-ext-sdk/pull/243

**Closed by nvladimirovi** 2022-02-14 10:30 UTC
