### ISSUE TITLE
Cannot build plugin

### ISSUE THREAD

**Issue by haovdnal** [vmware/vcd-ext-sdk#244] opened 2022-02-07 09:05 UTC
I created new plugin followed by instruction: https://vmware.github.io/vcd-ext-sdk/docs/development_examples/ticketing/
I can run it on localhost, now I want to release it on cloud production, I run `npm run build` to build zip file but dist/plugin.zip is not created without error
![Screen Shot 2022-02-07 at 16 04 17](https://user-images.githubusercontent.com/93630587/152757448-fe2da79c-db11-4353-99cb-3b5a1ded109c.png)

Any help?

**Comment by nvladimirovi** [comment] 2022-02-07 10:00
Hey @haovdnal,
Can you please try to run the build from inside your plugin folder? You should have 2 angular.json files in total in your project, so you have to run the command from within the "child" one. If there is no npm build command you can call the build using `ng` cli.

The issue here is when you build your plugin the exception gets masked out and you can't see it.

**Comment by haovdnal** [comment] 2022-02-07 11:11
@nvladimirovi 
Thank you so much
I built successful the plugin.

**Comment by nvladimirovi** [comment] 2022-02-07 13:20
@haovdnal Great! I'll close the issue feel free to re-open if something goes wrong.

**Comment by haovdnal** [comment] 2022-02-07 15:43
Hi @nvladimirovi ,
When my plugin just have uiplugin, dont have types, I can build plugin and install successfully on cloud production.
But then I ceate type Ticketing, I run it failed on production. 
You can see error on my image:
<img width="1904" alt="Screen Shot 2022-02-07 at 22 32 04" src="https://user-images.githubusercontent.com/93630587/152821076-47468954-3917-46df-82b2-3774193607ed.png">

**Comment by nvladimirovi** [comment] 2022-02-07 16:57
Do you see any other errors before those?
What is your Cloud Director Version?

**Comment by haovdnal** [comment] 2022-02-08 02:20
@nvladimirovi 
VMware Cloud Director version:
10.3.1.18738571 Oct 7, 2021, 7:57:34 AM GMT+7

I dont see any other error before. I installed plugin by upload plugin.zip to clould or run command `npm run deploy`.
Then I refresh page, it doesn't work like expect (dont show on menu, can not access module, page)

**Comment by nvladimirovi** [comment] 2022-02-08 07:58
Did you make any changes to the plugin seed? If yes, is it possible to post the diff somewhere?

**Comment by haovdnal** [comment] 2022-02-08 09:50
@nvladimirovi 
It seems the cause is package @vcd/ui-components. I don't know why and haven't fixed the error yet, but if I remove that library the error goes away.

Can you help to check it?

**Comment by nvladimirovi** [comment] 2022-02-08 12:23
Ohh... I think the problem is that @vcd/ui-components includes some testing code in their bundles and that causes the error.
@stoychevl Do we have a workaround for this?

**Comment by stoychevl** [comment] 2022-02-08 14:24
Hi @haovdnal 

I have done some local testing to confirm the issue is in relation to the @vcd/ui-components. Unfortunately I currently don't have a work around for the ticketing example, unless you are willing to currently develop without using this library. We are going to log an issue and update the ticketing example once we fix it.

Kind Regards,
Lyubo

**Comment by haovdnal** [comment] 2022-02-08 14:55
@stoychevl @nvladimirovi 
Thank you.
Please let me know when issue is fixed.

**Comment by nvladimirovi** [comment] 2022-02-08 16:02
Reopen based on @haovdnal [comment](https://github.com/vmware/vcd-ext-sdk/issues/244#issuecomment-1032698566)

**Comment by haovdnal** [comment] 2022-02-09 08:19
@nvladimirovi @stoychevl 
Today I used package material for UI (https://material.angular.io/guide/getting-started). I can still develop on my local, but when I deploy on production, It have error same when I using package @vcd/ui-components.

**Comment by nvladimirovi** [comment] 2022-02-25 11:22
Hey @haovdnal,
can you please try add the following in `ticketing/packages/uiPlugin/angular.json`:


"architect": {
        "build": {
          "builder": "@vcd/plugin-builders:plugin-builder",
          "options": {
            "modulePath": "src/main/ticketing.module.ts#TicketingPluginModule",
            "ignoreDefaultExternals": true,     <======= Add everything starting from here
            "externalLibs": [
              "@angular/common$",
              "@angular/common/http$",
              "@angular/core$",
              "@angular/forms$",
              "@angular/platform-browser$",
              "@angular/router$",
              "@clr/angular$",
              "@ngrx/store$",
              "rxjs$",
              "rxjs/internal-compatibility$",
              "rxjs/operators$"
            ],                          <======= To here
            ...
            ...
            
**Explaining**
Cloud Director exports the list of libraries that the Plugin can re-use in runtime, what is happening here is the following.
1. You are using dependency X
2. This dependency for some reason depends on @angular/testing
3. When the plugin gets loaded in vCD it "asks" for this dependency
4. vCD doesn't provide it (intentionally) and that's why you see the error.

**Comment by nvladimirovi** [comment] 2022-02-28 12:51
@haovdnal the issue has to be fixed, please re-open if you encounter any related issues.

**Closed by nvladimirovi** 2022-02-28 12:51 UTC
