### ISSUE TITLE
npm run start doesn't work

### ISSUE THREAD

**Issue by mkonopko997** [vmware/vcd-ext-sdk#242] opened 2021-11-18 10:30 UTC
I try to run the plugin locally and I get this error.
![image](https://user-images.githubusercontent.com/23666889/142397693-61b29ead-b69b-4b9e-9cd0-462d47287528.png)
Am I doing something wrong?

**Comment by oscarrodrigues** [comment] 2021-11-21 21:47
I was having the same problem.
The problem is in the execution of vcd-ext serves. The solution was to run "ng serve" directly, but first you will need to perform some settings manually.
I will explain the steps used to generate a project.

versions
npm - v6.14.4
node - v12.16.3
vcd-ext - v0.0.13-beta.1

note: I used versions based on the tutorial https://vmware.github.io/vcd-ext-sdk/docs/development_examples/ticketing/

1. Install the angle cli 9.1.12
`$ npm install -g @angular/cli@9.1.12`

2. Install vcd/ext-cli
`$ npm install -g @vcd/ext-cli@0.0.13-beta.1`

3. Create the project (in this case I'll call it mytest)
```
$ vcd-ext new

? Your solution name mytest
? Specify first version 0.0.1
? Specify vendor name MyTest
? Specify minimum required Cloud Director version
? Specify vendor link http://example.com
? Specify solution license BSD-2-Clause
? Select extensibility elements UI Plugin
? UI Plugin:element name uiPlugin
```

4. Manually create the .env/proxy.runtime.json file with the contents below.
```
{
    "/api/*": {
        "target": "https://<fqdn_your_vcloud>",
        "secure": false,
        "logLevel": "debug",
        "changeOrigin": true
    },
    "/cloudapi/*": {
        "target": "http//<fqdn_your_vcloud>",
        "secure": false,
        "logLevel": "debug",
        "changeOrigin": true
    }
}
```
5. Manually create the .env/.runtime.json file with the contents below.

```
{
    "production": true,
    "branding": {
        "headerTitle": "VMware Cloud Director"
    },
    "credentials": {
        "username": "<user_name>",
        "tenant": "<vcd_name>",
        "password": "<user_password>"
    }
}
```

6. Edit the angular.json file and fix the module name in lazyModules.
```
"lazyModules": [
    "packages/uiPlugin/src/main/mytest.module"
]
```

7.Configure the plugin loading file in the emulator.
```
[
    {
      "label": "MyTest",
      "root": "packages/uiPlugin/src",
      "module": "main/mytest.module#MytestPluginModule"
    }
]
```

8. Run the ng serve.
```
$ ng serves
```

> I try to run the plugin locally and I get this error. ![image](https://user-images.githubusercontent.com/23666889/142397693-61b29ead-b69b-4b9e-9cd0-462d47287528.png) Am I doing something wrong?

I was having the same problem.
The problem is in the execution of vcd-ext serves. The solution was to run "ng serve" directly, but first you will need to perform some settings manually.
I will explain the steps used to generate a project.

versions
npm - v6.14.4
node - v12.16.3
vcd-ext - v0.0.13-beta.1

note: I used versions based on the tutorial https://vmware.github.io/vcd-ext-sdk/docs/development_examples/ticketing/

    Install the angle cli 9.1.12
    $ npm install -g @angular/cli@9.1.12

    Install vcd/ext-cli
    $ npm install -g @vcd/ext-cli@0.0.13-beta.1

    Create the project (in this case I'll call it mytest)

$ vcd-ext new

? Your solution name mytest
? Specify first version 0.0.1
? Specify vendor name MyTest
? Specify minimum required Cloud Director version
? Specify vendor link http://example.com
? Specify solution license BSD-2-Clause
? Select extensibility elements UI Plugin
? UI Plugin:element name uiPlugin

    Manually create the .env/proxy.runtime.json file with the contents below.

{
    "/api/*": {
        "target": "https://<fqdn_your_vcloud>",
        "secure": false,
        "logLevel": "debug",
        "changeOrigin": true
    },
    "/cloudapi/*": {
        "target": "http//<fqdn_your_vcloud>",
        "secure": false,
        "logLevel": "debug",
        "changeOrigin": true
    }
}

    Manually create the .env/.runtime.json file with the contents below.

{
    "production": true,
    "branding": {
        "headerTitle": "VMware Cloud Director"
    },
    "credentials": {
        "username": "<user_name>",
        "tenant": "<vcd_name>",
        "password": "<user_password>"
    }
}

    Edit the angular.json file and fix the module name in lazyModules.

"lazyModules": [
    "packages/uiPlugin/src/main/mytest.module"
]

7.Configure the plugin loading file in the emulator.

[
    {
      "label": "MyTest",
      "root": "packages/uiPlugin/src",
      "module": "main/mytest.module#MytestPluginModule"
    }
]

    Run the ng serve.

$ ng serves

**Comment by mkonopko997** [comment] 2021-11-23 10:21
Hey, thanks for your answer.
I followed your steps but I still have some issues.
Had you this error?
![image](https://user-images.githubusercontent.com/23666889/143007158-f66d5d08-dca0-456e-8dc4-8df6f3230d5c.png)

**Comment by oscarrodrigues** [comment] 2021-11-23 18:51
This issue is fixed by step 6.
Check the angular.json file that the lazyModules parameter is within the correct structure. Also check the relative path to the module.
Below is part of the angular.json file.

   architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/emulator",
    	    ...            
            "scripts": [
              "node_modules/@webcomponents/custom-elements/custom-elements.min.js",
              "node_modules/@clr/icons/clr-icons.min.js",
              "node_modules/systemjs/dist/system.src.js"
            ],
           "lazyModules": [
              "packages/uiPlugin/src/main/mytest.module"
            ]
          },
          "configurations": {
    	      ...

**Comment by nvladimirovi** [comment] 2022-02-14 10:44
@oscarrodrigues Thank you for your support. Closing the issue since there is no activity, feel free to re-open.

**Closed by nvladimirovi** 2022-02-14 10:44 UTC
